services:
  postgres:
    container_name: postgres
    image: postgres:16
    pull_policy: always
    restart: always
    environment:
      POSTGRES_DB: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciso_assistant -d ciso_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    container_name: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    pull_policy: always
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ALLOWED_HOSTS=backend,localhost,agilciso.mitrakeluarga.com
      - CISO_ASSISTANT_URL=https://agilciso.mitrakeluarga.com:8443
      - DJANGO_DEBUG=False
      - AUTH_TOKEN_TTL=7200
      - POSTGRES_NAME=ciso_assistant
      - POSTGRES_USER=ciso_assistant
      - POSTGRES_PASSWORD=ciso_assistant
      - DB_HOST=postgres
    volumes:
      - ./db:/code/db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8000/api/build || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 100s
  huey:
    container_name: huey
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    pull_policy: always
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost
      - CISO_ASSISTANT_URL=https://agilciso.mitrakeluarga.com:8443
      - DJANGO_DEBUG=False
      - AUTH_TOKEN_TTL=7200
      - POSTGRES_NAME=ciso_assistant
      - POSTGRES_USER=ciso_assistant
      - POSTGRES_PASSWORD=ciso_assistant
      - DB_HOST=postgres
    volumes:
      - ./db:/code/db
    entrypoint:
      - /bin/sh
      - -c
      - |
        poetry run python manage.py run_huey -w 2 --scheduler-interval 60
  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://agilciso.mitrakeluarga.com:8443/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    pull_policy: always
    depends_on:
      backend:
        condition: service_healthy
  caddy:
    container_name: caddy
    image: caddy:2.8.4
    environment:
      - CISO_ASSISTANT_URL=https://agilciso.mitrakeluarga.com:8443
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - ./caddy_data:/data
    command: |
      sh -c 'echo $$CISO_ASSISTANT_URL "{
      reverse_proxy /api/* backend:8000
      reverse_proxy /* frontend:3000
      tls internal
      }" > Caddyfile && caddy run'